### PR TITLE
#157789345  Create user home page

### PR DESCRIPTION
**Pull request by johnmusiu**
### What does this PR do?
Adds a user home page.

### Description of tasks to be completed
Added table to show historical user maintenance requests

### How should this be manually tested?
- Clone or download the repo. 
- Navigate to the templates folder and open the home-user.html file on a browser of your choice.

### Any background context you want to provide?
No.

### What are the relevant Pivotal Tracker Stories?
[#157789345](https://www.pivotaltracker.com/story/show/157789345)

### Screenshot
image

### CODE REVIEW

**Comment by dessHub** [comment]
PR description is okay.

**Comment by joelmachango** [comment]
@johnmusiu Well documented PR. Add a background color/ image instead of a white background. I think it will make your design more appealing.

**Comment by gtsofa** [comment]
This PR wants to merge commits into **master** from **feature** branch.. That's not correct, fix this asap and make another PR for review

**Comment by johnmusiu** [comment]
@joelmachango thanks, the background is on another branch I havent merged with this one yet,

@gtsofa close catch, thanks.

**Comment by denniswanjiru** [comment]
Descriptive and follows recommended convention

**Pull request merged**
