### PR TITLE
#157768219 Add create maintenance request section 

### PR DESCRIPTION
**Pull request by johnmusiu**
### What does this PR do?
Create maintenance section on the user home page. The request input form only displays after 'Make Request' button is clicked.

### Description of tasks to be completed
Added a form with title and description input fields for creating new maintenance request.

### How should this be manually tested?
- Clone or download the repo. 
```$  git clone https://github.com/johnmusiu/Maintenance-Tracker/ ```
```$ git checkout ft-user-add-request-section-157768219```
- Navigate to the templates folder and open the home-user.html file on a browser of your choice.

### What are the relevant Pivotal Tracker Stories?
[#157768219](https://www.pivotaltracker.com/story/show/157768219)

### Questions?
- Is the togglable form a good design, with the button text change?

### Screenshots:
image

image

### CODE REVIEW

**Comment by Slinjez** [comment]
Nice UI, maybe you could increase opacity to something like 80%

**Comment by johnmusiu** [comment]
@Slinjez I have increased opacity for the form. It is more legible now. thanks

**Comment by artorious** [comment]
Great UI.  scales nicely.  I liked the carousel at home as well.

**Comment by Slinjez** [comment]
@johnmusiu yeah... this is it man, it's now readable and

**Pull request merged**
