### PR TITLE
[Finishes #157787790] Added admin review to approve or reject request

### PR DESCRIPTION
**Pull request by johnmusiu**
### What does this PR do?
Adds an admin request review section, decision submission links.

### Description of task completed?
Admin can expand and review details of a request.
Approve and reject links provided for admin decision.

### How should this be manually tested?
 - Clone or download the project
``` $ git clone https://github.com/johnmusiu/Maintenance-Tracker/tree/ft-admin-request-review-157787790 ```

 - Navigate to templates/ directory, then click the dashboard.html file to view the admin dashboard page on a browser.

- Open home-admin.html with your preferred browser

### Any background context you want to provide
Created using: HTML5 and CSS

### What is the relevant pivotal tracker stories?
[#157787790](https://www.pivotaltracker.com/story/show/157787790)

### Screen-shot
image

### CODE REVIEW

**Comment by lawrenceChege** [comment]
Nice UI design.
Great PR and commits
i like the middle part. how did you?

**Comment by johnmusiu** [comment]
I'll get you the links I used

https://www.w3schools.com/jsref/met_table_insertrow.asp
https://www.w3schools.com/jsref/coll_table_rows.asp
http://jsfiddle.net/4sR2G/

**Comment by maxwellgithinji** [comment]
@johnmusiu Like what you did with the UI, It looks great. Nice PR too.

**Comment by PaulKitonyi** [comment]
Wow the UI is cool.Great and detailed PR too.

**Comment by ghost** [comment]
Okay. So detailed PR. I guess it's becoming easier now. I would say that I've gotten some inspiration for my own admin page. But I feel like it could be simpler.

**Comment by johnmusiu** [comment]
@davenmathews Doing it right gets easier with time.

Yup , I think the UI could be simpler, I just had a good feeling about what I wanted to have implemented. Any suggestions on that front?

**Comment by Slinjez** [comment]
Impressive

**Pull request merged**
